// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwUULez4N0r9SMHdCST2rnopcfbROdRGY',
    appId: '1:216785981314:web:c90c683297a62ddb29499b',
    messagingSenderId: '216785981314',
    projectId: 'ditonton-final',
    authDomain: 'ditonton-final.firebaseapp.com',
    storageBucket: 'ditonton-final.appspot.com',
    measurementId: 'G-1474RDZFR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxTBxVuAHmBRwgFc-DekgQgvIvi1feuWI',
    appId: '1:216785981314:android:454fdd8c1690666329499b',
    messagingSenderId: '216785981314',
    projectId: 'ditonton-final',
    storageBucket: 'ditonton-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqla4ZwMtMCtespoHYKFrGkRKGNAc_hTc',
    appId: '1:216785981314:ios:17ad184d04634e5a29499b',
    messagingSenderId: '216785981314',
    projectId: 'ditonton-final',
    storageBucket: 'ditonton-final.appspot.com',
    iosClientId: '216785981314-422eq0bt1o30lhvuubmvnnecrp2888pv.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
